# آپ کی اپنی پرانی اور فاسٹ ریم سیٹنگ
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m

# Flutter Migrator Flags
android.builtInKotlin=false
android.newDsl=false

# AndroidX & Build Stability Flags (ایرز روکنے کے لیے)
android.useAndroidX=true
android.enableJetifier=true
android.suppressKotlinVersionCompatibilityCheck=true